apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: split-framework-observability

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus/prometheus.yml
  - name: kepler-config
    files:
      - kepler/config.yaml
  - name: grafana-datasources
    files:
      - grafana/datasources.yml
  - name: grafana-dashboards
    files:
      - grafana/dashboards.yml
  - name: grafana-dashboard-split-framework-live
    files:
      - grafana/split-framework-live.json

resources:
  - namespace.yaml
  - prometheus-deployment.yaml
  - grafana-deployment.yaml
  - cadvisor-daemonset.yaml
  - kepler-daemonset.yaml
