log:
  level: info
  format: text
host:
  sysfs: /host/sys
  procfs: /host/proc
monitor:
  interval: 5s
  staleness: 500ms
  maxTerminated: 100
cpu:
  meters: ["rapl", "hwmon", "fake"]
exporter:
  stdout:
    enabled: false
  prometheus:
    enabled: true
web:
  listenAddresses:
    - ":28282"
kube:
  enabled: false
